spring.application.name=parking-system

### DATABASE CONNECTION ###
spring.datasource.url=jdbc:mysql://localhost:3306/parking_project
spring.datasource.username=root
spring.datasource.password=admin

### JWT ###
# Th?i h?n c?a refreshToken là 30 ngày
parking.app.RefreshTokenExpirationDays=30

# Token bí m?t
parking.app.SecretKey=ParkingSystemSecretKeyMustBeVeryLongAndSecure2026!@#
# Th?i h?n c?a accessToken là 15 phút
parking.app.AccessTokenExpirationSeconds=900

# Tên c?a h?p Cookie dùng ?? ch?a access Token
parking.app.AccesssCookieName=parking-access-cookie
# Tên c?a h?p cookie dùng ?? ch?a refreshToken
parking.app.RefreshCookieName=parking-refresh-cookie


### JPA/HIBERNATE ###
spring.jpa.hibernate.ddl-auto=none

### SQL ###
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

